#!/bin/bash
#
# (c) 2012, Fraj KALLEL <frajkallel@gmail.com>
# Munin plugin to monitor the key_buffer_size variable of MySQL  server for optimize it if it's necessary
# running on the server.
#
#config example for /etc/munin/plugin-conf.d/munin-node
# [key_buffer_size]
# user root
# env.mysql_myi_files        /var/lib/mysql


if [ "$1" = "autoconf" ]; then
        echo yes
        exit 0
fi

if [ "$1" = "config" ]; then

echo "graph_title Mysql Key Buffer Size"
echo "graph_args -l 0"
echo "graph_category Mysql"
echo "graph_info  monitor the key_buffer_size variable of MySQL  server for optimize it if necessary"
echo "graph_vlabel MB"
echo "key_buffer_size.label key_buffer_size MB"
echo "key_buffer_size.type GAUGE"
echo "key_buffer_size.draw LINE2"

	exit 0

fi

cd $mysql_myi_files

MYI_SIZE_Kb=$(find . -name '*.MYI' -exec du '{}' \; 2>&1 | awk '{ s += $1 } END { printf("%.0f\n", s )}')

MYI_SIZE_Mb=$(( $MYI_SIZE_Kb/1024 ))

echo "key_buffer_size.value $MYI_SIZE_Mb"

